CREATE TABLE COUNTRY
(
    COUNTRY_ID SERIAL PRIMARY KEY,
    NAME       VARCHAR(255) NOT NULL
);

CREATE TABLE CITY
(
    CITY_ID SERIAL PRIMARY KEY,
    NAME    VARCHAR(255) NOT NULL
);

CREATE TABLE POI
(
    POI_ID        SERIAL PRIMARY KEY,
    LATITUDE      NUMERIC(14, 12) NOT NULL,
    LONGITUDE     NUMERIC(15, 12) NOT NULL,
    GEOHASH       VARCHAR(10)     NOT NULL,
    PARKING_PRICE NUMERIC(19, 2)  NOT NULL,
    CITY_ID       INTEGER         NOT NULL REFERENCES CITY (CITY_ID),
    COUNTRY_ID    INTEGER         NOT NULL REFERENCES COUNTRY (COUNTRY_ID)
);

CREATE INDEX IDX_POI_1 ON POI (LATITUDE, LONGITUDE, GEOHASH, CITY_ID);
CREATE INDEX IDX_POI_2 ON POI (GEOHASH);
